FIND_PATH (
	LIBTCC_INCLUDE_DIR
	NAMES
		libtcc.h
	HINTS
		$ENV{LIBTCC_ROOT}/include
		/usr/local/include
		/usr/include
)

FIND_LIBRARY (
	LIBTCC_LIBRARY
	NAMES
		tcc
	HINTS
		$ENV{LIBTCC_ROOT}/lib
		/usr/local/lib
		/usr/lib
    PATH_SUFFIXES
        x86_64-linux-gnu
        tcc
)

SET ( LIBTCC_LIBRARIES ${LIBTCC_LIBRARY} )
SET ( LIBTCC_INCLUDE_DIRS ${LIBTCC_INCLUDE_DIR} )

INCLUDE ( FindPackageHandleStandardArgs )
FIND_PACKAGE_HANDLE_STANDARD_ARGS (
    LibTCC DEFAULT_MSG
    LIBTCC_LIBRARY
    LIBTCC_INCLUDE_DIR
)

MARK_AS_ADVANCED (LIBTCC_INCLUDE_DIR LIBTCC_LIBRARY)
